### ISSUE TITLE
Prohibit linking to short linking services

### ISSUE THREAD

**Issue by rmorey** [oss/shrunk#25]
I pretty easily created two links which link back to each other in a loop (http://shrunk.rutgers.edu/40ht0r0a and http://shrunk.rutgers.edu/8gr86fpx). I believe most URL shortening services, like bit.ly, disalllow linking to other URL shortening services, and definitely to its own links. We should follow suit.

**Comment by ksuarz** [comment]
We need to take a look at how other URL shorteners prevent link loops. I want a fairly robust way to do it that doesn't consume too many resources as this can get really sophisticated.

**Comment by jungsoo** [comment]
I'm just going to add a check for shrunk's own linkserver for now.
