### ISSUE TITLE
URL validation is broken

### ISSUE THREAD

**Issue by rmorey** [oss/shrunk#26]
When creating a link, I can just put any garbage in and it goes through (ex: http://shrunk.rutgers.edu/8gr86fpx) 

However, when editing a link, the form is very strict about entering a valid URL, and it requires the http:// prefix. This is kinda annoying.

**Comment by ksuarz** [comment]
The strict URL validation is the fault of HTML5, which does strict URL validation in the browser to force all links to be external links (with the protocol). I disabled the validation and it now accepts everything.

We can get a custom amount of validation by passing it through Flask. I think it would be good for us to inspect the URL when it gets created and add in the protocol if it's not already present.
