### ISSUE TITLE
Alphabetical search searches by case first

### ISSUE THREAD

**Issue by jungsoo** [oss/shrunk#33]
It sorts A-Z first and then a-z.

**Comment by ksuarz** [comment]
This is a MongoDB issue: when sorting on a field, there is no case-insensitive search. We can fix this with an aggregation but it will change the way searches and queries are performed in the background.

**Comment by sakibj** [comment]
Got it boss

**Comment by sakibj** [comment]
Current issue: different pages sort independently.
