### ISSUE TITLE
Allow vanity links

### ISSUE THREAD

**Issue by ksuarz** [oss/shrunk#36]
Give users the option of specifying a name for their link. It should consider:

- Minimum and maximum possible name length
- No duplicates
- No banned names

**Comment by richton** [comment]
The banned names should probably have a regexp-like engine under the hood, so we can wildcard word stems, numb3r 5ub5titution, etc. Whether or not we overtly expose that on the web is another story, but the code should think w1th this in mind.

**Comment by ksuarz** [comment]
We'll look into allowing the administrators to use the web interface to customize what regular expressions get used in the filtering process.

**Comment by ksuarz** [comment]
@jungsoo it should now be easier to fix up the shrinking process to allow vanity links now that #41 is resolved.

**Comment by jungsoo** [comment]
The basic feature has been implemented. I'll leave this open as a reminder to also implement the regex.

**Comment by sakibj** [comment]
Remember to populate the form upon resubmits
