### ISSUE TITLE
Admin control panel options disappear

### ISSUE THREAD

**Issue by jungsoo** [oss/shrunk#43]
The admin control links in the sidebar disappear when accessing some of them.

**Comment by ksuarz** [comment]
Some of these are fixed in commits merged from `feature/admin-controls`; the block links page and the manage administrators page should be fixed. A future commit that retouches the user blacklist page will fix that.

**Comment by ksuarz** [comment]
This should be fixed in 93d92a189eb63ba20220a9723058e7f5732a26f1. (The issue was that the administrator pages were not telling the template that an admin was authenticated.)
