### ISSUE TITLE
statistics

### ISSUE THREAD

**Issue by mrjackchen-css** [oss/shrunk#52]
Be able to see which links were accessed inside the university and outside the university.

**Comment by sakibj** [comment]
Store IP addresses

**Comment by RutgersRoboticsResearch** [comment]
Did the Rutgers view count part. Might move on to more advanced statistics in the new /stats/<short_url_id> route.

**Comment by sakibj** [comment]
Added Rutgers view count to home page in new branch "stat."
Might move on to display more advanced statistics in the new /stats/<short_url_id> route.

**Comment by jungsoo** [comment]
is this done? we can add it to 1.0 if this is ready for packaging.

**Comment by sakibj** [comment]
yep
