### ISSUE TITLE
handle mongodb being unavailable

### ISSUE THREAD

**Issue by mrjackchen-css** [oss/shrunk#54]
- in the event that mongodb is not available, redirect to a maintenance page which includes the error code 5xx, 4xx, etc.

**Comment by ksuarz** [comment]
I'll take a sweep of our queries and also make sure the application is resilient in the event a read/write/update doesn't succeed. Currently we just assume that everything is successful.

**Comment by sakibj** [comment]
Mongo_stability branch merged
