### ISSUE TITLE
PAM Authentication

### ISSUE THREAD

**Issue by sakib** [oss/shrunk#58]
Redo the authentication on shrunk to talk pam:

http://twistedmatrix.com/pipermail/twisted-python/2006-May/013039.html
https://pypi.python.org/pypi/pysasl/

**Comment by jungsoo** [comment]
Test logging in with become accounts as:

username: announce
password: {netid}:{enigma password}

also: http://pastebin.com/W8f95sVK

**Comment by mjrb** [comment]
this is being solved in the next release of shrunk. the current dev version of shrunk has CAS/netid authentication
